### ISSUE TITLE
Remove the `DirichletBCMetaClass` from dxh

### ISSUE THREAD

**Issue by samcunliffe** [UCL/dxh#10]
> The meta classes have been removed from dolfinx about three month ago, see https://github.com/FEniCS/dolfinx/commit/44d612240ee3423add975b48ccb7f89920c394bd, which is causing problems for me as I'm running a more recent version of dolfinx.

**Comment by samcunliffe** [comment]
Straight removal? Or just fix [the import](https://github.com/UCL/dxh/blob/2602111341cbbd4c2ed92873e184534e9b94457a/src/dxh.py#L15) to work if not found and deprecate the function?

**Comment by matt-graham** [comment]
A bit hacky, but to maintain compatibility with current stable release (v0.6.0) and also current development version we could do something like

```Python
try:
    # For compatibility with dolfinx@0.6 try initially import old 
    # DirichletBCMetaClass name
    from dolfinx.fem import DirichletBCMetaClass as DirichletBC
except ImportError:
    from dolfinx.fem import DirichletBC
```

and update the type hint accordingly (as it's only used in a type hint I think the slightly misleading aliasing of `DirichletBCMetaClass` to `DirichletBC` shouldn't matter too much).
