### ISSUE TITLE
Allow for newer Python versions in `python_requires` and consider removing support for Python 3.9

### ISSUE THREAD

**Issue by matt-graham** [UCL/dxh#17]
Currently we require Python 3.9 or 3.10

https://github.com/UCL/dxh/blob/6466c60e18d9fec0cb0e7b8e308b44cb781222d8/pyproject.toml#L48

which I think is because previously this is the only Python versions there was `fenics-dolfinx` releases for on `conda-forge`. As `dxss` depends on `dxh` this also restrict the Python versions `dxss` can use. The v0.7.3 release of `fenics-dolfinx` has [package builds for Python 3.8 through to 3.12](https://anaconda.org/conda-forge/fenics-dolfinx/files) so we can relax the Python requirements here to allow any version after 3.9. Given by [NEP29 timeline current support would be for Python 3.10+](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table) we might also want to consider dropping support for Python 3.9 at the same time. This would also allow us to use for example the `X | Y` syntax for unions in type hints.

@samcunliffe do you have any thoughts on dropping Python 3.9 support?

**Comment by samcunliffe** [comment]
We _could_ always do 
```python
from __future__ import annotations
```
...and maintain 3.9 with the nice "or" syntax. 

But unless @janoschpreuss is using Python 3.9, I say: drop it. There's no reason -- as far as I can think -- to keep. And dropping makes us nicely ahead of the [Python support schedule](https://devguide.python.org/versions/). 

Even if we decide not to drop 3.9, should we add tests for a few more recent versions?
https://github.com/UCL/dxh/blob/6466c60e18d9fec0cb0e7b8e308b44cb781222d8/.github/workflows/tests.yml#L16

**Comment by matt-graham** [comment]
Resolved by #22
